[project]
name = "amech-proto"
version = "2024.6.18"
description = "Add a short description here"
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge", "auto-mech"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.10.*"
pip = "*"
# AutoChem dependencies
ipython = "*"
ipywidgets = "*"
jupyter = "*"
more-itertools = "*"
networkx = ">=3.3"
numpy = "*"
py3dmol = "*"
pyparsing = "*"
pyyaml = "*"
qcelemental = "*"
rdkit = "*"
scipy = "*"
xarray = "*"
# MechAnalyzer dependencies
click = "*"
matplotlib = "*"
pandera = ">=0.19.3,<0.20"
tqdm = ">=4.66.4,<4.67"
# Compiled AutoMech modules
mess-static = "*"

[system-requirements]
linux="3.10"

# Dev dependencies
[pypi-dependencies]
pip = "*"
pylint = "*"
pytest = "*"
pre-commit = "*"
black = "*"
ruff = "*"
mypy = "*"
sphinx = "*"
myst-parser = "*"
sphinx-book-theme = "*"
sphinx-autodoc-typehints = "*"
