[project]
name = "amech-proto"
version = "2024.6.18"
description = "Add a short description here"
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge", "auto-mech"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "*"
pip = "*"
# AutoChem dependencies
ipython = "*"
ipywidgets = "*"
jupyter = "*"
more-itertools = "*"
networkx = "*"
numpy = "*"
py3dmol = "*"
pylint = "*"
pyparsing = "*"
pytest = "*"
pyyaml = "*"
qcelemental = "*"
rdkit = "*"
scipy = "*"
xarray = "*"
# MechAnalyzer dependencies
click = "*"
matplotlib = "*"
# Compiled AutoMech modules
mess-static = "*"

[system-requirements]
linux="3.10"

