"""Data processing at the level of whole mechanisms."""

from . import data, io, old_net, schema, util
from ._mech import (
    Mechanism,
    add_reactions,
    are_equivalent,
    display,
    display_reactions,
    display_species,
    drop_parent_reactions,
    expand_parent_stereo,
    expand_stereo,
    from_data,
    from_network,
    from_smiles,
    from_string,
    neighborhood,
    rate_units,
    reaction_count,
    reaction_equations,
    reactions,
    remove_all_reactions,
    rename,
    rename_dict,
    set_rate_units,
    set_reactions,
    set_species,
    set_thermo_temperatures,
    species,
    species_count,
    species_names,
    species_network,
    string,
    thermo_temperatures,
    update_parent_reaction_data,
    update_parent_species_data,
    with_species,
    without_duplicate_reactions,
    without_unused_species,
)

__all__ = [
    # types
    "Mechanism",
    # functions
    "from_data",
    "from_network",
    "from_smiles",
    # getters
    "species",
    "reactions",
    "thermo_temperatures",
    "rate_units",
    # setters
    "set_species",
    "set_reactions",
    "set_thermo_temperatures",
    "set_rate_units",
    # properties
    "species_count",
    "reaction_count",
    "species_names",
    "reaction_equations",
    "rename_dict",
    "species_network",
    # transformations
    "rename",
    "remove_all_reactions",
    "add_reactions",
    "neighborhood",
    "with_species",
    "without_unused_species",
    "without_duplicate_reactions",
    "expand_stereo",
    "expand_parent_stereo",
    "drop_parent_reactions",
    "update_parent_species_data",
    "update_parent_reaction_data",
    # comparisons
    "are_equivalent",
    # read/write,
    "string",
    "from_string",
    # display
    "display",
    "display_species",
    "display_reactions",
    # modules
    "io",
    "data",
    "util",
    "schema",
    "old_net",
]
