name: lint

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Environment
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          environments: default dev

      - name: Pip install AutoChem
        run: |
          pixi run -e dev pip install git+https://github.com/Auto-Mech/autochem.git --no-deps

      # Lint
      - name: Lint
        run: |
          pixi run -e dev lint
